services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./src/database/init.db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      # - POSTGRES_DB=${DATABASE_NAME}

  app:
    image: sale-order-system-back
    container_name: nest-docker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /usr/src/app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
